services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/workspace:cached
    depends_on:
      - php
    networks:
      - laravel_dev_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../src:/workspace:cached
    working_dir: /workspace
    depends_on:
      - postgres
    networks:
      - laravel_dev_network

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - laravel_dev_network
    ports:
      - '5432:5432'

networks:
  laravel_dev_network:
    driver: bridge

volumes:
  postgres-data: